---
title: "JP Flores' resume"
author: JP Flores
date: "`r Sys.Date()`"
googlefonts: ["Tilt Prism"]
output:
  pagedown::html_resume:
      css:
        - custom.css  
        - resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    #self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
# knit: pagedown::chrome_print
---

# Aside

## Contact {#contact}

-   <i class="fa-solid fa-comments"></i> Pronouns: he/him
-   <i class="fa-solid fa-square-phone"></i> 661-993-2696
-   <i class="fa-solid fa-square-envelope"></i>
    [jpflores013\@gmail.com](mailto:jpflores013@gmail.com){.email}
-   <i class="fa-solid fa-house"></i> Carrboro, NC

## Links {#links}

-   <i class="fa fa-github"></i>
    [github.com/jpflores-13](https://github.com/jpflores-13)
-   <i class="fa-brands fa-linkedin"></i>
    [linkedin.com/in/john-patrick-flores](https://www.linkedin.com/in/john-patrick-flores/)
-   <i class="fa-brands fa-twitter"></i>
    [\@jpflores_13](https://twitter.com/jpflores_13)
-   <i class="fa-brands fa-orcid"></i>
    [0000-0001-5619-8990](https://orcid.org/my-orcid?orcid=0000-0001-5619-8990)

## Skills & Training {#skills}

- **Effective Mentoring Training** (2022)

- **Programming languages** including R, Python, bash scripting, HTML, and CSS

- **Workflow management** tools such as Make, Snakemake, and Nextflow using Docker and Git for reproducibility.

- **High-performance computing** environments

- **Strong understanding of large, complex NGS data types** such as Hi-C/Micro-C, RNA, SLAM, CUT&RUN, ChiP, ATAC

- **Confident** working in highly collaborative, fast-paced environments.

## Awards & Accolades {#awards}

- [**Occidental's 18 Young Scientists to Watch** (2023)](https://www.oxy.edu/magazine/issues/spring-2023/18-young-scientists-watch)
- [**UNC Department of Genetics Retreat Poster Award** (2022)](https://bcb.unc.edu/2022/09/16/john-flores-receives-top-poster-award-at-2022-scientific-retreat/)
- [**National Science Foundation (NSF) Graduate Research Fellowship Program (GRFP)** (2022)](https://www.oxy.edu/academics/student-success/national-international-fellowships/fellowships-stories/john-patrick)
- [**Spotify Next Wave Award Winner** (2021)](https://podcasters.spotify.com/resources/news)
- [**Trevor Moawad Leadership Award** (2021)](https://www.oxy.edu/news/tiger-club-athletics-awards-announced-2021)
- [**Dean’s Award: Service** (2021)](https://www.oxy.edu/news/deans-award-winners-2021)
- [**Capstone Student Leader of the Year Award** (2021)](https://www.oxy.edu/news/2021-student-leadership-awards-honor-exemplary-undergraduates)
- [**Lucille Y. Gilman Memorial Award** (2021)](https://www.oxy.edu/commencement/class-2021-highlights/senior-class-day-awards-2021)
- **John W. McMenamin Award** (2021)

# Main

## JP Flores {#title}

### PhD Candidate in Bioinformatics & Computational Biology

#### Computational Biologist with expertise in high-throughput genomics, multiplexed imaging, data visualization, and science communication. I'm passionate about innovation in science and the diversity, equity, and inclusion (DEI) space. {#summary}

## Education {data-icon="graduation-cap" data-concise="true"}

### PhD in Bioinformatics and Computational Biology

The University of North Carolina at Chapel Hill

N/A

2021 - present

Graduate Certificate in Innovation for the Public Good

Advisor: Doug Phanstiel

### BA in Cellular & Molecular Biology 

Occidental College, Los Angeles, CA

N/A

2017 - 2021

Public Health and Critical Theory & Social Justice Minors

## Experience {data-icon="laptop"}

### Graduate Research Assistant

Phanstiel Lab (UNC-CH School of Medicine)

Chapel Hill, NC

2022 - Present

- Using computational and wet-lab techniques to investigate the role of 3D chromatin architecture in response to environmental stress. 
- Developing a user interface for the R/Bioconductor data visualization packager, plotgardener

### Undergraduate Researcher

Schulz Lab (Occidental College Department of Biology)

Los Angeles, CA

2017 - 2021

- Utilize techniques such as DNA isolation, PCR, gel electrophoresis, and HPLC to find medical relevance of venom. 
- Conduct fieldwork in Kauai to study and capture venomous cone snails. 

## <i class="fa-solid fa-folder-open"></i> Featured Work {data-icon="NULL"}
### [**From where does it STEM?**](https://open.spotify.com/show/1KLdFOVbk70n2qAz6zcdv2?si=97783437144f4e7a)

Host/Creator

N/A

N/A

A podcast that empowers the next generation of diverse scientists.

### the people of posit: bringing personality to R packages {#posit}
Invited talk at posit::conf(2023)

N/A

N/A

#### Chicago, Illinois {#chicago}

### Hyperosmotic stress induces phase-separation-driven chromatin loops
Poster presentation at the Keystone Symposium: Chromatin Architecture in Human Disease & Development 

N/A

N/A

#### Victoria, British Columbia

### Hyperosmotic stress induces complete rewiring of chromatin interactions
Poster presentation at the Fifth Annual Dr. Samuel M. Nabrit Conference for Early Career Scholars 

N/A

N/A

#### Providence, Rhode Island {#providence}

### Hyperosmotic stress induces complete rewiring of chromatin interactions
Poster presentation at the 10th Annual Mid-Atlantic PREP & IMSD Research Symposium 

N/A

N/A

#### Blacksburg, Virginia {#blacksburg}